import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar/>
        <marquee className="bg-blue-300 w-full p-2">
          <h1>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequatur illum earum molestiae consequuntur quae fugit autem culpa nulla saepe corporis?
          </h1>
        </marquee>
        {children}
        <Footer/>
        <Toaster />
      </body>
    </html>
  );
}
